[[redirects]]
  from = "/weeknotes/"
  to = "https://tanvibhakta.mataroa.blog"
  status = 302
  force = true


[[redirects]]
  from = "/resume/"
  to = "https://tanvibhakta.in/resume.pdf"
  status = 301
  force = true

[[redirects]]
  from = "/code/"
  to = "https://github.com/tanvibhakta"
  status = 301
  force = true
